//! core message, model, and provider types

use derive_more::{AsRef, Deref, Display, From};
use serde::{Deserialize, Deserializer, Serialize};

// -- string newtypes --

/// unique model identifier (e.g. "claude-sonnet-4-20250514")
#[derive(
    Debug, Clone, PartialEq, Eq, Hash, Display, From, Deref, AsRef, Serialize, Deserialize,
)]
pub struct ModelId(String);

impl From<&str> for ModelId {
    fn from(s: &str) -> Self {
        Self(s.to_string())
    }
}

/// unique tool call identifier generated by the provider
#[derive(
    Debug, Clone, PartialEq, Eq, Hash, Display, From, Deref, AsRef, Serialize, Deserialize,
)]
pub struct ToolCallId(String);

impl From<&str> for ToolCallId {
    fn from(s: &str) -> Self {
        Self(s.to_string())
    }
}

/// tool name (e.g. "Read", "Bash")
#[derive(
    Debug, Clone, PartialEq, Eq, Hash, Display, From, Deref, AsRef, Serialize, Deserialize,
)]
pub struct ToolName(String);

impl From<&str> for ToolName {
    fn from(s: &str) -> Self {
        Self(s.to_string())
    }
}

/// stable session identifier shared across crates
#[derive(
    Debug, Clone, PartialEq, Eq, Hash, Display, From, Deref, AsRef, Serialize, Deserialize,
)]
pub struct SessionId(String);

impl From<&str> for SessionId {
    fn from(s: &str) -> Self {
        Self(s.to_string())
    }
}

impl SessionId {
    pub fn new() -> Self {
        use std::sync::atomic::{AtomicU64, Ordering};
        static COUNTER: AtomicU64 = AtomicU64::new(0);
        let time = Timestamp::now().as_ms();
        let count = COUNTER.fetch_add(1, Ordering::Relaxed);
        let pid = std::process::id() as u64;
        let id = time
            .wrapping_mul(6364136223846793005)
            .wrapping_add(pid)
            .wrapping_add(count);
        Self(format!("{id:016x}"))
    }
}

impl Default for SessionId {
    fn default() -> Self {
        Self::new()
    }
}

/// unique pane identifier shared across tui and session state
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Display, From, Serialize, Deserialize,
)]
pub struct PaneId(u32);

impl PaneId {
    pub const fn new(id: u32) -> Self {
        Self(id)
    }

    pub const fn as_u32(self) -> u32 {
        self.0
    }
}

/// millisecond unix timestamp
#[derive(
    Debug,
    Clone,
    Copy,
    Default,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Hash,
    Display,
    Serialize,
    Deserialize,
)]
pub struct Timestamp(u64);

impl Timestamp {
    pub const fn zero() -> Self {
        Self(0)
    }

    pub const fn from_ms(ms: u64) -> Self {
        Self(ms)
    }

    pub fn now() -> Self {
        Self(
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_millis() as u64,
        )
    }

    pub fn as_ms(&self) -> u64 {
        self.0
    }

    /// format as a human-readable relative age (e.g. "30s", "5m", "2h")
    #[must_use]
    pub fn age_display(&self) -> String {
        let now = Self::now().as_ms();
        let then = self.0;
        if now <= then {
            return "now".into();
        }
        let secs = (now - then) / 1000;
        if secs < 60 {
            return format!("{secs}s");
        }
        let mins = secs / 60;
        if mins < 60 {
            return format!("{mins}m");
        }
        let hours = mins / 60;
        if hours < 24 {
            return format!("{hours}h");
        }
        let days = hours / 24;
        if days < 7 {
            return format!("{days}d");
        }
        let weeks = days / 7;
        if days < 30 {
            return format!("{weeks}w");
        }
        let months = days / 30;
        if days < 365 {
            return format!("{months}mo");
        }
        let years = days / 365;
        format!("{years}y")
    }
}

// -- token count --

/// token count used in context windows, usage stats, and compaction thresholds.
/// wraps u64 to prevent mixing with arbitrary integers
#[derive(
    Debug,
    Clone,
    Copy,
    Default,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Hash,
    Display,
    Serialize,
    Deserialize,
)]
pub struct TokenCount(u64);

impl TokenCount {
    pub const ZERO: Self = Self(0);

    pub const fn new(n: u64) -> Self {
        Self(n)
    }

    pub const fn get(self) -> u64 {
        self.0
    }

    /// percentage of a context window this count represents
    pub fn percent_of(self, window: Self) -> f64 {
        if window.0 == 0 {
            return 0.0;
        }
        (self.0 as f64 / window.0 as f64) * 100.0
    }

    /// whether this count exceeds a fraction of a context window
    pub fn exceeds_fraction(self, window: Self, numerator: u64, denominator: u64) -> bool {
        self.0 * denominator > window.0 * numerator
    }
}

impl From<u64> for TokenCount {
    fn from(n: u64) -> Self {
        Self(n)
    }
}

impl From<usize> for TokenCount {
    fn from(n: usize) -> Self {
        Self(n as u64)
    }
}

impl std::ops::Add for TokenCount {
    type Output = Self;
    fn add(self, rhs: Self) -> Self {
        Self(self.0 + rhs.0)
    }
}

impl std::ops::AddAssign for TokenCount {
    fn add_assign(&mut self, rhs: Self) {
        self.0 += rhs.0;
    }
}

// -- dollars --

/// monetary cost in US dollars.
/// wraps f64 to prevent mixing cost-per-million with actual dollar amounts
#[derive(Debug, Clone, Copy, Default, PartialEq, PartialOrd, Serialize, Deserialize)]
pub struct Dollars(f64);

impl Dollars {
    pub const ZERO: Self = Self(0.0);

    pub const fn new(amount: f64) -> Self {
        Self(amount)
    }

    pub const fn get(self) -> f64 {
        self.0
    }
}

impl std::fmt::Display for Dollars {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "${:.4}", self.0)
    }
}

impl From<f64> for Dollars {
    fn from(n: f64) -> Self {
        Self(n)
    }
}

impl std::ops::Add for Dollars {
    type Output = Self;
    fn add(self, rhs: Self) -> Self {
        Self(self.0 + rhs.0)
    }
}

impl std::ops::AddAssign for Dollars {
    fn add_assign(&mut self, rhs: Self) {
        self.0 += rhs.0;
    }
}

// -- validated newtypes --

/// a base URL for an API endpoint (trailing slash stripped on construction)
#[derive(Debug, Clone, PartialEq, Eq, Hash, Display, Deref, Serialize, Deserialize)]
pub struct BaseUrl(String);

impl BaseUrl {
    #[must_use]
    pub fn new(url: impl Into<String>) -> Self {
        let s = url.into();
        Self(s.trim_end_matches('/').to_string())
    }

    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// append a path segment to the base URL
    #[must_use]
    pub fn join(&self, path: &str) -> String {
        format!("{}/{}", self.0, path.trim_start_matches('/'))
    }
}

impl From<&str> for BaseUrl {
    fn from(s: &str) -> Self {
        Self::new(s)
    }
}

impl From<String> for BaseUrl {
    fn from(s: String) -> Self {
        Self::new(s)
    }
}

/// an API key (redacted in Debug/Display, non-empty when present)
#[derive(Clone, Serialize, Deserialize)]
pub struct ApiKey(String);

impl ApiKey {
    #[must_use]
    pub fn new(key: impl Into<String>) -> Option<Self> {
        let s = key.into();
        if s.is_empty() { None } else { Some(Self(s)) }
    }

    /// explicitly access the raw secret value
    ///
    /// use this only when you genuinely need the key (auth headers,
    /// token inspection). Display and Debug are redacted by design
    #[must_use]
    pub fn expose(&self) -> &str {
        &self.0
    }

    /// whether this looks like an anthropic oauth token
    #[must_use]
    pub fn is_oauth_token(&self) -> bool {
        self.0.contains("sk-ant-oat")
    }
}

impl std::fmt::Debug for ApiKey {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        if self.0.chars().count() > 8 {
            let prefix: String = self.0.chars().take(4).collect();
            write!(f, "ApiKey({prefix}...)")
        } else {
            write!(f, "ApiKey(***)")
        }
    }
}

impl std::fmt::Display for ApiKey {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "***")
    }
}

impl PartialEq for ApiKey {
    fn eq(&self, other: &Self) -> bool {
        self.0 == other.0
    }
}

impl Eq for ApiKey {}

/// temperature for LLM sampling (clamped to 0.0..=2.0)
#[derive(Debug, Clone, Copy, PartialEq, PartialOrd, Serialize, Deserialize)]
pub struct Temperature(f32);

impl Temperature {
    pub const MIN: f32 = 0.0;
    pub const MAX: f32 = 2.0;

    #[must_use]
    pub fn new(value: f32) -> Self {
        Self(value.clamp(Self::MIN, Self::MAX))
    }

    #[must_use]
    pub fn value(self) -> f32 {
        self.0
    }
}

impl From<f32> for Temperature {
    fn from(v: f32) -> Self {
        Self::new(v)
    }
}

// -- content types --

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TextContent {
    pub text: String,
}

/// thinking block in an assistant message
#[derive(Debug, Clone, PartialEq)]
pub enum ThinkingContent {
    /// normal thinking with text and optional signature for multi-turn continuity
    Thinking {
        thinking: String,
        signature: Option<String>,
    },
    /// redacted thinking, opaque signature only
    Redacted { data: String },
}

impl ThinkingContent {
    /// the thinking text, or a placeholder for redacted blocks
    pub fn text(&self) -> &str {
        match self {
            Self::Thinking { thinking, .. } => thinking,
            Self::Redacted { .. } => "[reasoning redacted]",
        }
    }

    /// mutable access to the thinking text (only for non-redacted)
    pub fn text_mut(&mut self) -> Option<&mut String> {
        match self {
            Self::Thinking { thinking, .. } => Some(thinking),
            Self::Redacted { .. } => None,
        }
    }

    /// the signature, if any
    pub fn signature(&self) -> Option<&str> {
        match self {
            Self::Thinking { signature, .. } => signature.as_deref(),
            Self::Redacted { data } => Some(data),
        }
    }

    /// mutable access to the signature slot (only for non-redacted)
    pub fn signature_mut(&mut self) -> Option<&mut Option<String>> {
        match self {
            Self::Thinking { signature, .. } => Some(signature),
            Self::Redacted { .. } => None,
        }
    }

    pub fn is_redacted(&self) -> bool {
        matches!(self, Self::Redacted { .. })
    }
}

impl Serialize for ThinkingContent {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeMap;
        match self {
            Self::Thinking {
                thinking,
                signature,
            } => {
                let len = 2 + signature.is_some() as usize;
                let mut map = serializer.serialize_map(Some(len))?;
                map.serialize_entry("thinking", thinking)?;
                map.serialize_entry("redacted", &false)?;
                if let Some(sig) = signature {
                    map.serialize_entry("signature", sig)?;
                }
                map.end()
            }
            Self::Redacted { data } => {
                let mut map = serializer.serialize_map(Some(3))?;
                map.serialize_entry("thinking", "[reasoning redacted]")?;
                map.serialize_entry("redacted", &true)?;
                map.serialize_entry("signature", data)?;
                map.end()
            }
        }
    }
}

impl<'de> Deserialize<'de> for ThinkingContent {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        #[derive(Deserialize)]
        struct Raw {
            thinking: String,
            #[serde(default)]
            redacted: bool,
            signature: Option<String>,
        }
        let raw = Raw::deserialize(deserializer)?;
        if raw.redacted {
            Ok(Self::Redacted {
                data: raw.signature.unwrap_or_default(),
            })
        } else {
            Ok(Self::Thinking {
                thinking: raw.thinking,
                signature: raw.signature,
            })
        }
    }
}

/// supported image mime types
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ImageMimeType {
    #[serde(rename = "image/jpeg")]
    Jpeg,
    #[serde(rename = "image/png")]
    Png,
    #[serde(rename = "image/gif")]
    Gif,
    #[serde(rename = "image/webp")]
    Webp,
}

impl ImageMimeType {
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Jpeg => "image/jpeg",
            Self::Png => "image/png",
            Self::Gif => "image/gif",
            Self::Webp => "image/webp",
        }
    }

    /// parse from file extension (defaults to png)
    #[must_use]
    pub fn from_extension(ext: &str) -> Self {
        match ext.to_lowercase().as_str() {
            "jpg" | "jpeg" => Self::Jpeg,
            "gif" => Self::Gif,
            "webp" => Self::Webp,
            _ => Self::Png,
        }
    }
}

impl std::fmt::Display for ImageMimeType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ImageContent {
    /// base64 encoded image data
    pub data: String,
    pub mime_type: ImageMimeType,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ToolCall {
    pub id: ToolCallId,
    pub name: ToolName,
    pub arguments: serde_json::Value,
}

// -- user content --

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum UserContent {
    Text(String),
    Parts(Vec<UserContentPart>),
}

impl UserContent {
    /// extract the text content, joining text parts if multipart
    #[must_use]
    pub fn text(&self) -> String {
        match self {
            Self::Text(t) => t.clone(),
            Self::Parts(parts) => parts
                .iter()
                .filter_map(|p| match p {
                    UserContentPart::Text(t) => Some(t.text.as_str()),
                    _ => None,
                })
                .collect::<Vec<_>>()
                .join(" "),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum UserContentPart {
    Text(TextContent),
    Image(ImageContent),
}

// -- assistant content --

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum AssistantContentPart {
    Text(TextContent),
    Thinking(ThinkingContent),
    ToolCall(ToolCall),
}

// -- tool result content --

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ToolResultContentPart {
    Text(TextContent),
    Image(ImageContent),
}

// -- usage --

#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize, PartialEq)]
pub struct Usage {
    pub input_tokens: TokenCount,
    pub output_tokens: TokenCount,
    pub cache_read_tokens: TokenCount,
    pub cache_write_tokens: TokenCount,
}

impl Usage {
    /// total tokens processed in this API call (all categories)
    pub fn total_tokens(&self) -> TokenCount {
        self.input_tokens + self.output_tokens + self.cache_read_tokens + self.cache_write_tokens
    }

    /// total input tokens (context size for this call).
    /// for anthropic: input_tokens is non-cached, cache_read + cache_write are the rest
    pub fn total_input_tokens(&self) -> TokenCount {
        self.input_tokens + self.cache_read_tokens + self.cache_write_tokens
    }
}

#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize, PartialEq)]
pub struct Cost {
    pub input: Dollars,
    pub output: Dollars,
    pub cache_read: Dollars,
    pub cache_write: Dollars,
}

impl Cost {
    pub fn total(&self) -> Dollars {
        self.input + self.output + self.cache_read + self.cache_write
    }
}

// -- stop reason --

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
#[non_exhaustive]
pub enum StopReason {
    Stop,
    Length,
    ToolUse,
    Error,
    Aborted,
}

// -- messages --

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct UserMessage {
    pub content: UserContent,
    pub timestamp_ms: Timestamp,
}

impl UserMessage {
    /// extract the text content of this message
    #[must_use]
    pub fn text(&self) -> String {
        self.content.text()
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AssistantMessage {
    pub content: Vec<AssistantContentPart>,
    pub model: ModelId,
    pub provider: Provider,
    pub api: Api,
    pub usage: Usage,
    pub stop_reason: StopReason,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    pub timestamp_ms: Timestamp,
}

impl AssistantMessage {
    /// extract concatenated text content (excludes thinking and tool calls)
    #[must_use]
    pub fn text(&self) -> String {
        self.content
            .iter()
            .filter_map(|p| match p {
                AssistantContentPart::Text(t) if !t.text.is_empty() => Some(t.text.as_str()),
                _ => None,
            })
            .collect::<Vec<_>>()
            .join("")
    }

    /// extract the thinking text, if any
    #[must_use]
    pub fn thinking(&self) -> Option<String> {
        self.content.iter().find_map(|p| match p {
            AssistantContentPart::Thinking(t) => Some(t.text().to_string()),
            _ => None,
        })
    }
}

/// whether a tool execution succeeded or failed
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[must_use]
pub enum ToolOutcome {
    Success,
    Error,
}

impl ToolOutcome {
    #[must_use]
    pub fn is_error(self) -> bool {
        self == Self::Error
    }

    #[must_use]
    pub fn is_success(self) -> bool {
        self == Self::Success
    }
}

impl From<bool> for ToolOutcome {
    fn from(is_error: bool) -> Self {
        if is_error { Self::Error } else { Self::Success }
    }
}

/// deserialise from either `"outcome": "success"` or legacy `"is_error": true`
fn deserialise_outcome<'de, D: Deserializer<'de>>(d: D) -> Result<ToolOutcome, D::Error> {
    #[derive(Deserialize)]
    #[serde(untagged)]
    enum Raw {
        Enum(ToolOutcome),
        Bool(bool),
    }
    match Raw::deserialize(d)? {
        Raw::Enum(o) => Ok(o),
        Raw::Bool(b) => Ok(ToolOutcome::from(b)),
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ToolResultMessage {
    pub tool_call_id: ToolCallId,
    pub tool_name: ToolName,
    pub content: Vec<ToolResultContentPart>,
    #[serde(alias = "is_error", deserialize_with = "deserialise_outcome")]
    pub outcome: ToolOutcome,
    pub timestamp_ms: Timestamp,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "role", rename_all = "snake_case")]
pub enum Message {
    User(UserMessage),
    Assistant(AssistantMessage),
    ToolResult(ToolResultMessage),
}

// -- api + provider --

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "kebab-case")]
pub enum Api {
    AnthropicMessages,
    OpenaiCompletions,
    OpenaiResponses,
}

/// known first-party providers
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "kebab-case")]
pub enum Provider {
    Anthropic,
    OpenRouter,
    #[serde(untagged)]
    Custom(String),
}

impl std::fmt::Display for Provider {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Anthropic => write!(f, "anthropic"),
            Self::OpenRouter => write!(f, "openrouter"),
            Self::Custom(name) => write!(f, "{name}"),
        }
    }
}

// -- model + cost --

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ModelCost {
    /// cost per million input tokens
    pub input: f64,
    /// cost per million output tokens
    pub output: f64,
    /// cost per million cache read tokens
    pub cache_read: f64,
    /// cost per million cache write tokens
    pub cache_write: f64,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum InputModality {
    Text,
    Image,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Model {
    pub id: ModelId,
    pub name: String,
    pub api: Api,
    pub provider: Provider,
    pub base_url: BaseUrl,
    pub reasoning: bool,
    pub input: Vec<InputModality>,
    pub cost: ModelCost,
    pub context_window: TokenCount,
    pub max_output_tokens: TokenCount,
}

// -- thinking level --

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ThinkingLevel {
    Off,
    Minimal,
    Low,
    Medium,
    High,
    Xhigh,
}

impl ThinkingLevel {
    /// Keep `Minimal` for compatibility with older configs/runtime state, but
    /// treat it as `Low` in visible mush controls and persisted visible prefs.
    #[must_use]
    pub const fn normalize_visible(self) -> Self {
        match self {
            Self::Minimal => Self::Low,
            other => other,
        }
    }
}

// -- stream options --

#[derive(Debug, Clone, Default)]
pub struct StreamOptions {
    pub temperature: Option<Temperature>,
    pub max_tokens: Option<TokenCount>,
    pub api_key: Option<ApiKey>,
    pub thinking: Option<ThinkingLevel>,
    /// stable session identifier for provider-side prompt caching
    pub session_id: Option<SessionId>,
    /// optional account id for providers that need account-scoped headers
    pub account_id: Option<String>,
    /// prompt cache retention preference for providers that support it
    pub cache_retention: Option<CacheRetention>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum CacheRetention {
    None,
    Short,
    Long,
}

/// strategy for trimming old tool results in the message array
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ToolResultTrimming {
    /// trim old tool results at request time using a sliding window.
    /// suitable for models/providers without prompt caching
    #[default]
    SlidingWindow,
    /// never trim tool results at request time, preserving prefix stability
    /// for providers with prompt caching (anthropic, etc.)
    Preserve,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn usage_total_tokens() {
        let usage = Usage {
            input_tokens: TokenCount::new(100),
            output_tokens: TokenCount::new(50),
            cache_read_tokens: TokenCount::new(25),
            cache_write_tokens: TokenCount::new(10),
        };
        assert_eq!(usage.total_tokens(), TokenCount::new(185));
    }

    #[test]
    fn usage_total_input_tokens() {
        let usage = Usage {
            input_tokens: TokenCount::new(100),
            output_tokens: TokenCount::new(50),
            cache_read_tokens: TokenCount::new(25),
            cache_write_tokens: TokenCount::new(10),
        };
        // input + cache_read + cache_write, excludes output
        assert_eq!(usage.total_input_tokens(), TokenCount::new(135));
    }

    #[test]
    fn cost_total() {
        let cost = Cost {
            input: Dollars::new(0.003),
            output: Dollars::new(0.015),
            cache_read: Dollars::new(0.001),
            cache_write: Dollars::new(0.002),
        };
        assert!((cost.total().get() - 0.021).abs() < f64::EPSILON);
    }

    #[test]
    fn message_serialisation_roundtrip() {
        let msg = Message::User(UserMessage {
            content: UserContent::Text("hello".into()),
            timestamp_ms: Timestamp::from_ms(1_234_567_890),
        });
        let json = serde_json::to_string(&msg).unwrap();
        let back: Message = serde_json::from_str(&json).unwrap();
        assert_eq!(msg, back);
    }

    #[test]
    fn thinking_level_normalize_visible_maps_minimal_to_low() {
        assert_eq!(
            ThinkingLevel::Minimal.normalize_visible(),
            ThinkingLevel::Low
        );
        assert_eq!(ThinkingLevel::High.normalize_visible(), ThinkingLevel::High);
    }

    #[test]
    fn api_serde() {
        let json = serde_json::to_string(&Api::AnthropicMessages).unwrap();
        assert_eq!(json, r#""anthropic-messages""#);
    }

    #[test]
    fn stop_reason_serde() {
        let json = serde_json::to_string(&StopReason::ToolUse).unwrap();
        assert_eq!(json, r#""tool_use""#);
    }

    #[test]
    fn base_url_strips_trailing_slash() {
        let url = BaseUrl::new("https://api.example.com/v1/");
        assert_eq!(url.as_str(), "https://api.example.com/v1");
    }

    #[test]
    fn base_url_join() {
        let url = BaseUrl::new("https://api.example.com/v1");
        assert_eq!(url.join("messages"), "https://api.example.com/v1/messages");
    }

    #[test]
    fn base_url_deref_to_str() {
        let url = BaseUrl::new("https://api.example.com");
        assert!(url.contains("example"));
    }

    #[test]
    fn api_key_redacted_debug() {
        let key = ApiKey::new("sk-ant-api-abcdefghijk").unwrap();
        let debug = format!("{key:?}");
        assert!(!debug.contains("abcdefghijk"));
        assert!(debug.contains("sk-a..."));
    }

    #[test]
    fn api_key_empty_returns_none() {
        assert!(ApiKey::new("").is_none());
    }

    #[test]
    fn api_key_oauth_detection() {
        let oauth = ApiKey::new("sk-ant-oat-abc123").unwrap();
        assert!(oauth.is_oauth_token());
        let regular = ApiKey::new("sk-ant-api-abc123").unwrap();
        assert!(!regular.is_oauth_token());
    }

    #[test]
    fn temperature_clamps_to_range() {
        assert_eq!(Temperature::new(-1.0).value(), 0.0);
        assert_eq!(Temperature::new(0.7).value(), 0.7);
        assert_eq!(Temperature::new(5.0).value(), 2.0);
    }

    #[test]
    fn temperature_from_f32() {
        let t: Temperature = 0.5.into();
        assert_eq!(t.value(), 0.5);
    }

    #[test]
    fn tool_outcome_serialises_as_enum() {
        let json = serde_json::to_string(&ToolOutcome::Error).unwrap();
        assert_eq!(json, r#""error""#);
        let json = serde_json::to_string(&ToolOutcome::Success).unwrap();
        assert_eq!(json, r#""success""#);
    }

    #[test]
    fn tool_result_message_deserialises_legacy_is_error() {
        let json = r#"{
            "tool_call_id": "tc_1",
            "tool_name": "bash",
            "content": [],
            "is_error": true,
            "timestamp_ms": 0
        }"#;
        let msg: ToolResultMessage = serde_json::from_str(json).unwrap();
        assert!(msg.outcome.is_error());

        let json = r#"{
            "tool_call_id": "tc_2",
            "tool_name": "read",
            "content": [],
            "is_error": false,
            "timestamp_ms": 0
        }"#;
        let msg: ToolResultMessage = serde_json::from_str(json).unwrap();
        assert!(msg.outcome.is_success());
    }

    #[test]
    fn tool_result_message_deserialises_new_outcome() {
        let json = r#"{
            "tool_call_id": "tc_1",
            "tool_name": "bash",
            "content": [],
            "outcome": "error",
            "timestamp_ms": 0
        }"#;
        let msg: ToolResultMessage = serde_json::from_str(json).unwrap();
        assert!(msg.outcome.is_error());
    }

    #[test]
    fn tool_outcome_from_bool() {
        assert_eq!(ToolOutcome::from(true), ToolOutcome::Error);
        assert_eq!(ToolOutcome::from(false), ToolOutcome::Success);
    }

    #[test]
    fn thinking_content_serde_roundtrip() {
        let normal = ThinkingContent::Thinking {
            thinking: "let me think".into(),
            signature: Some("sig123".into()),
        };
        let json = serde_json::to_string(&normal).unwrap();
        let back: ThinkingContent = serde_json::from_str(&json).unwrap();
        assert_eq!(normal, back);
        assert!(!back.is_redacted());
        assert_eq!(back.text(), "let me think");
        assert_eq!(back.signature(), Some("sig123"));
    }

    #[test]
    fn thinking_content_redacted_serde_roundtrip() {
        let redacted = ThinkingContent::Redacted {
            data: "opaque_data".into(),
        };
        let json = serde_json::to_string(&redacted).unwrap();
        let back: ThinkingContent = serde_json::from_str(&json).unwrap();
        assert_eq!(redacted, back);
        assert!(back.is_redacted());
        assert_eq!(back.text(), "[reasoning redacted]");
        assert_eq!(back.signature(), Some("opaque_data"));
    }

    #[test]
    fn thinking_content_deserialises_legacy_format() {
        // legacy format with redacted: false
        let json = r#"{"thinking": "hello", "signature": "sig", "redacted": false}"#;
        let tc: ThinkingContent = serde_json::from_str(json).unwrap();
        assert!(!tc.is_redacted());
        assert_eq!(tc.text(), "hello");

        // legacy format with redacted: true
        let json = r#"{"thinking": "[reasoning redacted]", "signature": "data", "redacted": true}"#;
        let tc: ThinkingContent = serde_json::from_str(json).unwrap();
        assert!(tc.is_redacted());
        assert_eq!(tc.signature(), Some("data"));

        // legacy format without redacted field (defaults to false)
        let json = r#"{"thinking": "no redacted field"}"#;
        let tc: ThinkingContent = serde_json::from_str(json).unwrap();
        assert!(!tc.is_redacted());
        assert_eq!(tc.text(), "no redacted field");
    }

    #[test]
    fn age_display_seconds() {
        let now = Timestamp::now().as_ms();
        let ts = Timestamp::from_ms(now - 30_000);
        assert_eq!(ts.age_display(), "30s");
    }

    #[test]
    fn age_display_minutes() {
        let now = Timestamp::now().as_ms();
        let ts = Timestamp::from_ms(now - 300_000);
        assert_eq!(ts.age_display(), "5m");
    }

    #[test]
    fn age_display_hours() {
        let now = Timestamp::now().as_ms();
        let ts = Timestamp::from_ms(now - 7_200_000);
        assert_eq!(ts.age_display(), "2h");
    }

    #[test]
    fn age_display_days() {
        let now = Timestamp::now().as_ms();
        let ts = Timestamp::from_ms(now - 172_800_000);
        assert_eq!(ts.age_display(), "2d");
    }

    #[test]
    fn age_display_future_is_now() {
        let ts = Timestamp::from_ms(Timestamp::now().as_ms() + 10_000);
        assert_eq!(ts.age_display(), "now");
    }
}
