//! core message, model, and provider types

use derive_more::{AsRef, Deref, Display, From};
use serde::{Deserialize, Serialize};

// -- string newtypes --

/// unique model identifier (e.g. "claude-sonnet-4-20250514")
#[derive(
    Debug, Clone, PartialEq, Eq, Hash, Display, From, Deref, AsRef, Serialize, Deserialize,
)]
pub struct ModelId(String);

impl From<&str> for ModelId {
    fn from(s: &str) -> Self {
        Self(s.to_string())
    }
}

/// unique tool call identifier generated by the provider
#[derive(
    Debug, Clone, PartialEq, Eq, Hash, Display, From, Deref, AsRef, Serialize, Deserialize,
)]
pub struct ToolCallId(String);

impl From<&str> for ToolCallId {
    fn from(s: &str) -> Self {
        Self(s.to_string())
    }
}

/// tool name (e.g. "Read", "Bash")
#[derive(
    Debug, Clone, PartialEq, Eq, Hash, Display, From, Deref, AsRef, Serialize, Deserialize,
)]
pub struct ToolName(String);

impl From<&str> for ToolName {
    fn from(s: &str) -> Self {
        Self(s.to_string())
    }
}

/// millisecond unix timestamp
#[derive(
    Debug,
    Clone,
    Copy,
    Default,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Hash,
    Display,
    Serialize,
    Deserialize,
)]
pub struct Timestamp(u64);

impl Timestamp {
    pub const fn zero() -> Self {
        Self(0)
    }

    pub const fn from_ms(ms: u64) -> Self {
        Self(ms)
    }

    pub fn now() -> Self {
        Self(
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_millis() as u64,
        )
    }

    pub fn as_ms(&self) -> u64 {
        self.0
    }
}

// -- validated newtypes --

/// a base URL for an API endpoint (trailing slash stripped on construction)
#[derive(Debug, Clone, PartialEq, Eq, Hash, Display, Deref, Serialize, Deserialize)]
pub struct BaseUrl(String);

impl BaseUrl {
    pub fn new(url: impl Into<String>) -> Self {
        let s = url.into();
        Self(s.trim_end_matches('/').to_string())
    }

    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// append a path segment to the base URL
    pub fn join(&self, path: &str) -> String {
        format!("{}/{}", self.0, path.trim_start_matches('/'))
    }
}

impl From<&str> for BaseUrl {
    fn from(s: &str) -> Self {
        Self::new(s)
    }
}

impl From<String> for BaseUrl {
    fn from(s: String) -> Self {
        Self::new(s)
    }
}

/// an API key (redacted in Debug/Display, non-empty when present)
#[derive(Clone, Serialize, Deserialize)]
pub struct ApiKey(String);

impl ApiKey {
    pub fn new(key: impl Into<String>) -> Option<Self> {
        let s = key.into();
        if s.is_empty() { None } else { Some(Self(s)) }
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// whether this looks like an anthropic oauth token
    pub fn is_oauth_token(&self) -> bool {
        self.0.contains("sk-ant-oat")
    }
}

impl std::fmt::Debug for ApiKey {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        if self.0.len() > 8 {
            write!(f, "ApiKey({}...)", &self.0[..4])
        } else {
            write!(f, "ApiKey(***)")
        }
    }
}

impl std::fmt::Display for ApiKey {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "***")
    }
}

impl std::ops::Deref for ApiKey {
    type Target = str;
    fn deref(&self) -> &str {
        &self.0
    }
}

impl PartialEq for ApiKey {
    fn eq(&self, other: &Self) -> bool {
        self.0 == other.0
    }
}

impl Eq for ApiKey {}

/// temperature for LLM sampling (clamped to 0.0..=2.0)
#[derive(Debug, Clone, Copy, PartialEq, PartialOrd, Serialize, Deserialize)]
pub struct Temperature(f32);

impl Temperature {
    pub const MIN: f32 = 0.0;
    pub const MAX: f32 = 2.0;

    pub fn new(value: f32) -> Self {
        Self(value.clamp(Self::MIN, Self::MAX))
    }

    pub fn value(self) -> f32 {
        self.0
    }
}

impl From<f32> for Temperature {
    fn from(v: f32) -> Self {
        Self::new(v)
    }
}

// -- content types --

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TextContent {
    pub text: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ThinkingContent {
    pub thinking: String,
    /// opaque signature for multi-turn continuity
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signature: Option<String>,
    #[serde(default)]
    pub redacted: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ImageContent {
    /// base64 encoded image data
    pub data: String,
    /// eg "image/png", "image/jpeg"
    pub mime_type: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ToolCall {
    pub id: ToolCallId,
    pub name: ToolName,
    pub arguments: serde_json::Value,
}

// -- user content --

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum UserContent {
    Text(String),
    Parts(Vec<UserContentPart>),
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum UserContentPart {
    Text(TextContent),
    Image(ImageContent),
}

// -- assistant content --

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum AssistantContentPart {
    Text(TextContent),
    Thinking(ThinkingContent),
    ToolCall(ToolCall),
}

// -- tool result content --

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ToolResultContentPart {
    Text(TextContent),
    Image(ImageContent),
}

// -- usage --

#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize, PartialEq)]
pub struct Usage {
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub cache_read_tokens: u64,
    pub cache_write_tokens: u64,
}

impl Usage {
    /// total tokens processed in this API call (all categories)
    pub fn total_tokens(&self) -> u64 {
        self.input_tokens + self.output_tokens + self.cache_read_tokens + self.cache_write_tokens
    }

    /// total input tokens (context size for this call).
    /// for anthropic: input_tokens is non-cached, cache_read + cache_write are the rest
    pub fn total_input_tokens(&self) -> u64 {
        self.input_tokens + self.cache_read_tokens + self.cache_write_tokens
    }
}

#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize, PartialEq)]
pub struct Cost {
    pub input: f64,
    pub output: f64,
    pub cache_read: f64,
    pub cache_write: f64,
}

impl Cost {
    pub fn total(&self) -> f64 {
        self.input + self.output + self.cache_read + self.cache_write
    }
}

// -- stop reason --

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum StopReason {
    Stop,
    Length,
    ToolUse,
    Error,
    Aborted,
}

// -- messages --

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct UserMessage {
    pub content: UserContent,
    pub timestamp_ms: Timestamp,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AssistantMessage {
    pub content: Vec<AssistantContentPart>,
    pub model: ModelId,
    pub provider: Provider,
    pub api: Api,
    pub usage: Usage,
    pub stop_reason: StopReason,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    pub timestamp_ms: Timestamp,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ToolResultMessage {
    pub tool_call_id: ToolCallId,
    pub tool_name: ToolName,
    pub content: Vec<ToolResultContentPart>,
    pub is_error: bool,
    pub timestamp_ms: Timestamp,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "role", rename_all = "snake_case")]
pub enum Message {
    User(UserMessage),
    Assistant(AssistantMessage),
    ToolResult(ToolResultMessage),
}

// -- api + provider --

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "kebab-case")]
pub enum Api {
    AnthropicMessages,
    OpenaiCompletions,
    OpenaiResponses,
}

/// known first-party providers
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "kebab-case")]
pub enum Provider {
    Anthropic,
    OpenRouter,
    #[serde(untagged)]
    Custom(String),
}

impl std::fmt::Display for Provider {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Anthropic => write!(f, "anthropic"),
            Self::OpenRouter => write!(f, "openrouter"),
            Self::Custom(name) => write!(f, "{name}"),
        }
    }
}

// -- model + cost --

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ModelCost {
    /// cost per million input tokens
    pub input: f64,
    /// cost per million output tokens
    pub output: f64,
    /// cost per million cache read tokens
    pub cache_read: f64,
    /// cost per million cache write tokens
    pub cache_write: f64,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum InputModality {
    Text,
    Image,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Model {
    pub id: ModelId,
    pub name: String,
    pub api: Api,
    pub provider: Provider,
    pub base_url: BaseUrl,
    pub reasoning: bool,
    pub input: Vec<InputModality>,
    pub cost: ModelCost,
    pub context_window: u64,
    pub max_output_tokens: u64,
}

// -- thinking level --

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ThinkingLevel {
    Off,
    Minimal,
    Low,
    Medium,
    High,
    Xhigh,
}

// -- stream options --

#[derive(Debug, Clone, Default)]
pub struct StreamOptions {
    pub temperature: Option<Temperature>,
    pub max_tokens: Option<u64>,
    pub api_key: Option<ApiKey>,
    pub thinking: Option<ThinkingLevel>,
    /// stable session identifier for provider-side prompt caching
    pub session_id: Option<String>,
    /// optional account id for providers that need account-scoped headers
    pub account_id: Option<String>,
    /// prompt cache retention preference for providers that support it
    pub cache_retention: Option<CacheRetention>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum CacheRetention {
    None,
    Short,
    Long,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn usage_total_tokens() {
        let usage = Usage {
            input_tokens: 100,
            output_tokens: 50,
            cache_read_tokens: 25,
            cache_write_tokens: 10,
        };
        assert_eq!(usage.total_tokens(), 185);
    }

    #[test]
    fn usage_total_input_tokens() {
        let usage = Usage {
            input_tokens: 100,
            output_tokens: 50,
            cache_read_tokens: 25,
            cache_write_tokens: 10,
        };
        // input + cache_read + cache_write, excludes output
        assert_eq!(usage.total_input_tokens(), 135);
    }

    #[test]
    fn cost_total() {
        let cost = Cost {
            input: 0.003,
            output: 0.015,
            cache_read: 0.001,
            cache_write: 0.002,
        };
        assert!((cost.total() - 0.021).abs() < f64::EPSILON);
    }

    #[test]
    fn message_serialisation_roundtrip() {
        let msg = Message::User(UserMessage {
            content: UserContent::Text("hello".into()),
            timestamp_ms: Timestamp::from_ms(1234567890),
        });
        let json = serde_json::to_string(&msg).unwrap();
        let back: Message = serde_json::from_str(&json).unwrap();
        assert_eq!(msg, back);
    }

    #[test]
    fn api_serde() {
        let json = serde_json::to_string(&Api::AnthropicMessages).unwrap();
        assert_eq!(json, r#""anthropic-messages""#);
    }

    #[test]
    fn stop_reason_serde() {
        let json = serde_json::to_string(&StopReason::ToolUse).unwrap();
        assert_eq!(json, r#""tool_use""#);
    }

    #[test]
    fn base_url_strips_trailing_slash() {
        let url = BaseUrl::new("https://api.example.com/v1/");
        assert_eq!(url.as_str(), "https://api.example.com/v1");
    }

    #[test]
    fn base_url_join() {
        let url = BaseUrl::new("https://api.example.com/v1");
        assert_eq!(url.join("messages"), "https://api.example.com/v1/messages");
    }

    #[test]
    fn base_url_deref_to_str() {
        let url = BaseUrl::new("https://api.example.com");
        assert!(url.contains("example"));
    }

    #[test]
    fn api_key_redacted_debug() {
        let key = ApiKey::new("sk-ant-api-abcdefghijk").unwrap();
        let debug = format!("{key:?}");
        assert!(!debug.contains("abcdefghijk"));
        assert!(debug.contains("sk-a..."));
    }

    #[test]
    fn api_key_empty_returns_none() {
        assert!(ApiKey::new("").is_none());
    }

    #[test]
    fn api_key_oauth_detection() {
        let oauth = ApiKey::new("sk-ant-oat-abc123").unwrap();
        assert!(oauth.is_oauth_token());
        let regular = ApiKey::new("sk-ant-api-abc123").unwrap();
        assert!(!regular.is_oauth_token());
    }

    #[test]
    fn temperature_clamps_to_range() {
        assert_eq!(Temperature::new(-1.0).value(), 0.0);
        assert_eq!(Temperature::new(0.7).value(), 0.7);
        assert_eq!(Temperature::new(5.0).value(), 2.0);
    }

    #[test]
    fn temperature_from_f32() {
        let t: Temperature = 0.5.into();
        assert_eq!(t.value(), 0.5);
    }
}
