//! string newtypes, validated wrappers, and unit types

use derive_more::{AsRef, Deref, Display, From};
use serde::{Deserialize, Serialize};

/// unique model identifier (e.g. "claude-sonnet-4-20250514")
#[derive(
    Debug, Clone, PartialEq, Eq, Hash, Display, From, Deref, AsRef, Serialize, Deserialize,
)]
pub struct ModelId(String);

impl From<&str> for ModelId {
    fn from(s: &str) -> Self {
        Self(s.to_string())
    }
}

impl ModelId {
    /// short form for status bar display
    ///
    /// abbreviates alphabetic segments to first letter, keeps numbers as-is:
    /// `claude-opus-4-6` → `c-o-4-6`, `gpt-5.3-codex` → `g-5.3-c`
    pub fn abbreviated(&self) -> String {
        fn abbreviate_part(s: &str) -> String {
            s.split('-')
                .map(|seg| {
                    if seg.chars().all(|c| c.is_ascii_alphabetic()) {
                        seg[..1].to_string()
                    } else {
                        seg.to_string()
                    }
                })
                .collect::<Vec<_>>()
                .join("-")
        }

        if let Some((prefix, rest)) = self.0.split_once('/') {
            format!("{}/{}", abbreviate_part(prefix), abbreviate_part(rest))
        } else {
            abbreviate_part(&self.0)
        }
    }
}

/// unique tool call identifier generated by the provider
#[derive(
    Debug, Clone, PartialEq, Eq, Hash, Display, From, Deref, AsRef, Serialize, Deserialize,
)]
pub struct ToolCallId(String);

impl From<&str> for ToolCallId {
    fn from(s: &str) -> Self {
        Self(s.to_string())
    }
}

/// tool name (e.g. "Read", "Bash")
#[derive(
    Debug, Clone, PartialEq, Eq, Hash, Display, From, Deref, AsRef, Serialize, Deserialize,
)]
pub struct ToolName(String);

impl From<&str> for ToolName {
    fn from(s: &str) -> Self {
        Self(s.to_string())
    }
}

/// stable session identifier shared across crates
#[derive(
    Debug, Clone, PartialEq, Eq, Hash, Display, From, Deref, AsRef, Serialize, Deserialize,
)]
pub struct SessionId(String);

impl From<&str> for SessionId {
    fn from(s: &str) -> Self {
        Self(s.to_string())
    }
}

impl SessionId {
    pub fn new() -> Self {
        use std::sync::atomic::{AtomicU64, Ordering};
        static COUNTER: AtomicU64 = AtomicU64::new(0);
        let time = Timestamp::now().as_ms();
        let count = COUNTER.fetch_add(1, Ordering::Relaxed);
        let pid = std::process::id() as u64;
        let id = time
            .wrapping_mul(6364136223846793005)
            .wrapping_add(pid)
            .wrapping_add(count);
        Self(format!("{id:016x}"))
    }
}

impl Default for SessionId {
    fn default() -> Self {
        Self::new()
    }
}

/// unique pane identifier shared across tui and session state
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Display, From, Serialize, Deserialize,
)]
pub struct PaneId(u32);

impl PaneId {
    pub const fn new(id: u32) -> Self {
        Self(id)
    }

    pub const fn as_u32(self) -> u32 {
        self.0
    }
}

/// millisecond unix timestamp
#[derive(
    Debug,
    Clone,
    Copy,
    Default,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Hash,
    Display,
    Serialize,
    Deserialize,
)]
pub struct Timestamp(u64);

impl Timestamp {
    pub const fn zero() -> Self {
        Self(0)
    }

    pub const fn from_ms(ms: u64) -> Self {
        Self(ms)
    }

    pub fn now() -> Self {
        Self(
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_millis() as u64,
        )
    }

    pub fn as_ms(&self) -> u64 {
        self.0
    }

    /// format as a human-readable relative age (e.g. "30s", "5m", "2h")
    #[must_use]
    pub fn age_display(&self) -> String {
        let now = Self::now().as_ms();
        let then = self.0;
        if now <= then {
            return "now".into();
        }
        let secs = (now - then) / 1000;
        if secs < 60 {
            return format!("{secs}s");
        }
        let mins = secs / 60;
        if mins < 60 {
            return format!("{mins}m");
        }
        let hours = mins / 60;
        if hours < 24 {
            return format!("{hours}h");
        }
        let days = hours / 24;
        if days < 7 {
            return format!("{days}d");
        }
        let weeks = days / 7;
        if days < 30 {
            return format!("{weeks}w");
        }
        let months = days / 30;
        if days < 365 {
            return format!("{months}mo");
        }
        let years = days / 365;
        format!("{years}y")
    }
}

/// token count used in context windows, usage stats, and compaction thresholds.
/// wraps u64 to prevent mixing with arbitrary integers
#[derive(
    Debug,
    Clone,
    Copy,
    Default,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Hash,
    Display,
    Serialize,
    Deserialize,
)]
pub struct TokenCount(u64);

impl TokenCount {
    pub const ZERO: Self = Self(0);

    pub const fn new(n: u64) -> Self {
        Self(n)
    }

    pub const fn get(self) -> u64 {
        self.0
    }

    /// percentage of a context window this count represents
    pub fn percent_of(self, window: Self) -> f64 {
        if window.0 == 0 {
            return 0.0;
        }
        (self.0 as f64 / window.0 as f64) * 100.0
    }

    /// whether this count exceeds a fraction of a context window
    pub fn exceeds_fraction(self, window: Self, numerator: u64, denominator: u64) -> bool {
        self.0 * denominator > window.0 * numerator
    }
}

impl From<u64> for TokenCount {
    fn from(n: u64) -> Self {
        Self(n)
    }
}

impl From<usize> for TokenCount {
    fn from(n: usize) -> Self {
        Self(n as u64)
    }
}

impl std::ops::Add for TokenCount {
    type Output = Self;
    fn add(self, rhs: Self) -> Self {
        Self(self.0 + rhs.0)
    }
}

impl std::ops::AddAssign for TokenCount {
    fn add_assign(&mut self, rhs: Self) {
        self.0 += rhs.0;
    }
}

impl std::ops::Sub for TokenCount {
    type Output = Self;
    fn sub(self, rhs: Self) -> Self {
        Self(self.0.saturating_sub(rhs.0))
    }
}

impl std::ops::SubAssign for TokenCount {
    fn sub_assign(&mut self, rhs: Self) {
        self.0 = self.0.saturating_sub(rhs.0);
    }
}

/// monetary cost in US dollars.
/// wraps f64 to prevent mixing cost-per-million with actual dollar amounts
#[derive(Debug, Clone, Copy, Default, PartialEq, PartialOrd, Serialize, Deserialize)]
pub struct Dollars(f64);

impl Dollars {
    pub const ZERO: Self = Self(0.0);

    pub const fn new(amount: f64) -> Self {
        Self(amount)
    }

    pub const fn get(self) -> f64 {
        self.0
    }
}

impl std::fmt::Display for Dollars {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "${:.4}", self.0)
    }
}

impl From<f64> for Dollars {
    fn from(n: f64) -> Self {
        Self(n)
    }
}

impl std::ops::Add for Dollars {
    type Output = Self;
    fn add(self, rhs: Self) -> Self {
        Self(self.0 + rhs.0)
    }
}

impl std::ops::AddAssign for Dollars {
    fn add_assign(&mut self, rhs: Self) {
        self.0 += rhs.0;
    }
}

impl std::ops::Sub for Dollars {
    type Output = Self;
    fn sub(self, rhs: Self) -> Self {
        Self(self.0 - rhs.0)
    }
}

impl std::ops::SubAssign for Dollars {
    fn sub_assign(&mut self, rhs: Self) {
        self.0 -= rhs.0;
    }
}

/// a base URL for an API endpoint (trailing slash stripped on construction)
#[derive(Debug, Clone, PartialEq, Eq, Hash, Display, Deref, Serialize, Deserialize)]
pub struct BaseUrl(String);

impl BaseUrl {
    #[must_use]
    pub fn new(url: impl Into<String>) -> Self {
        let s = url.into();
        Self(s.trim_end_matches('/').to_string())
    }

    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// append a path segment to the base URL
    #[must_use]
    pub fn join(&self, path: &str) -> String {
        format!("{}/{}", self.0, path.trim_start_matches('/'))
    }
}

impl From<&str> for BaseUrl {
    fn from(s: &str) -> Self {
        Self::new(s)
    }
}

impl From<String> for BaseUrl {
    fn from(s: String) -> Self {
        Self::new(s)
    }
}

/// an API key (redacted in Debug/Display, non-empty when present)
#[derive(Clone, Serialize, Deserialize)]
pub struct ApiKey(String);

impl ApiKey {
    #[must_use]
    pub fn new(key: impl Into<String>) -> Option<Self> {
        let s = key.into();
        if s.is_empty() { None } else { Some(Self(s)) }
    }

    /// explicitly access the raw secret value
    ///
    /// use this only when you genuinely need the key (auth headers,
    /// token inspection). Display and Debug are redacted by design
    #[must_use]
    pub fn expose(&self) -> &str {
        &self.0
    }

    /// whether this looks like an anthropic oauth token
    #[must_use]
    pub fn is_oauth_token(&self) -> bool {
        self.0.contains("sk-ant-oat")
    }
}

impl std::fmt::Debug for ApiKey {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        if self.0.chars().count() > 8 {
            let prefix: String = self.0.chars().take(4).collect();
            write!(f, "ApiKey({prefix}...)")
        } else {
            write!(f, "ApiKey(***)")
        }
    }
}

impl std::fmt::Display for ApiKey {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "***")
    }
}

impl PartialEq for ApiKey {
    fn eq(&self, other: &Self) -> bool {
        self.0 == other.0
    }
}

impl Eq for ApiKey {}

/// temperature for LLM sampling (clamped to 0.0..=2.0)
#[derive(Debug, Clone, Copy, PartialEq, PartialOrd, Serialize, Deserialize)]
pub struct Temperature(f32);

impl Temperature {
    pub const MIN: f32 = 0.0;
    pub const MAX: f32 = 2.0;

    #[must_use]
    pub fn new(value: f32) -> Self {
        Self(value.clamp(Self::MIN, Self::MAX))
    }

    #[must_use]
    pub fn value(self) -> f32 {
        self.0
    }
}

impl From<f32> for Temperature {
    fn from(v: f32) -> Self {
        Self::new(v)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn model_id_abbreviated() {
        let cases = [
            ("claude-opus-4-6", "c-o-4-6"),
            ("claude-sonnet-4-20250514", "c-s-4-20250514"),
            ("claude-haiku-4-5", "c-h-4-5"),
            ("gpt-5.2", "g-5.2"),
            ("gpt-5.4", "g-5.4"),
            ("gpt-5.3-codex", "g-5.3-c"),
            ("anthropic/claude-sonnet-4", "a/c-s-4"),
            ("google/gemini-2.5-pro", "g/g-2.5-p"),
            ("google/gemini-2.5-flash", "g/g-2.5-f"),
            ("test", "t"),
            ("o3-mini", "o3-m"),
        ];
        for (input, expected) in cases {
            let id = ModelId::from(input);
            assert_eq!(id.abbreviated(), expected, "abbreviating {input}");
        }
    }

    #[test]
    fn base_url_strips_trailing_slash() {
        let url = BaseUrl::new("https://api.example.com/v1/");
        assert_eq!(url.as_str(), "https://api.example.com/v1");
    }

    #[test]
    fn base_url_join() {
        let url = BaseUrl::new("https://api.example.com/v1");
        assert_eq!(url.join("messages"), "https://api.example.com/v1/messages");
    }

    #[test]
    fn base_url_deref_to_str() {
        let url = BaseUrl::new("https://api.example.com");
        assert!(url.contains("example"));
    }

    #[test]
    fn api_key_redacted_debug() {
        let key = ApiKey::new("sk-ant-api-abcdefghijk").unwrap();
        let debug = format!("{key:?}");
        assert!(!debug.contains("abcdefghijk"));
        assert!(debug.contains("sk-a..."));
    }

    #[test]
    fn api_key_empty_returns_none() {
        assert!(ApiKey::new("").is_none());
    }

    #[test]
    fn api_key_oauth_detection() {
        let oauth = ApiKey::new("sk-ant-oat-abc123").unwrap();
        assert!(oauth.is_oauth_token());
        let regular = ApiKey::new("sk-ant-api-abc123").unwrap();
        assert!(!regular.is_oauth_token());
    }

    #[test]
    fn temperature_clamps_to_range() {
        assert_eq!(Temperature::new(-1.0).value(), 0.0);
        assert_eq!(Temperature::new(0.7).value(), 0.7);
        assert_eq!(Temperature::new(5.0).value(), 2.0);
    }

    #[test]
    fn temperature_from_f32() {
        let t: Temperature = 0.5.into();
        assert_eq!(t.value(), 0.5);
    }

    #[test]
    fn age_display_seconds() {
        let now = Timestamp::now().as_ms();
        let ts = Timestamp::from_ms(now - 30_000);
        assert_eq!(ts.age_display(), "30s");
    }

    #[test]
    fn age_display_minutes() {
        let now = Timestamp::now().as_ms();
        let ts = Timestamp::from_ms(now - 300_000);
        assert_eq!(ts.age_display(), "5m");
    }

    #[test]
    fn age_display_hours() {
        let now = Timestamp::now().as_ms();
        let ts = Timestamp::from_ms(now - 7_200_000);
        assert_eq!(ts.age_display(), "2h");
    }

    #[test]
    fn age_display_days() {
        let now = Timestamp::now().as_ms();
        let ts = Timestamp::from_ms(now - 172_800_000);
        assert_eq!(ts.age_display(), "2d");
    }

    #[test]
    fn age_display_future_is_now() {
        let ts = Timestamp::from_ms(Timestamp::now().as_ms() + 10_000);
        assert_eq!(ts.age_display(), "now");
    }

    #[test]
    fn token_count_sub() {
        let a = TokenCount::new(100);
        let b = TokenCount::new(30);
        assert_eq!(a - b, TokenCount::new(70));
    }

    #[test]
    fn token_count_sub_assign() {
        let mut a = TokenCount::new(100);
        a -= TokenCount::new(25);
        assert_eq!(a, TokenCount::new(75));
    }

    #[test]
    fn dollars_sub() {
        let a = Dollars::new(1.5);
        let b = Dollars::new(0.5);
        assert!(((a - b).get() - 1.0).abs() < f64::EPSILON);
    }

    #[test]
    fn dollars_sub_assign() {
        let mut a = Dollars::new(2.0);
        a -= Dollars::new(0.75);
        assert!((a.get() - 1.25).abs() < f64::EPSILON);
    }
}
